<?php
return [
    "countries" => array(
        "AF" => "Afghanistan",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua and Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia",
        "BA" => "Bosnia and Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "BQ" => "British Antarctic Territory",
        "IO" => "British Indian Ocean Territory",
        "VG" => "British Virgin Islands",
        "BN" => "Brunei",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CT" => "Canton and Enderbury Islands",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CC" => "Cocos [Keeling] Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo - Brazzaville",
        "CD" => "Congo - Kinshasa",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "CI" => "Côte d’Ivoire",
        "DK" => "Denmark",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "NQ" => "Dronning Maud Land",
        "DD" => "East Germany",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands",
        "FO" => "Faroe Islands",
        "FJ" => "Fiji",
        "FI" => "Finland",
        "FR" => "France",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Territories",
        "FQ" => "French Southern and Antarctic Territories",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germany",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island and McDonald Islands",
        "HN" => "Honduras",
        "HK" => "Hong Kong SAR China",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran",
        "IQ" => "Iraq",
        "IE" => "Ireland",
        "IM" => "Isle of Man",
        "IL" => "Israel",
        "IT" => "Italy",
        "JM" => "Jamaica",
        "JP" => "Japan",
        "JE" => "Jersey",
        "JT" => "Johnston Island",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Laos",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LY" => "Libya",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "MO" => "Macau SAR China",
        "MK" => "Macedonia",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "FX" => "Metropolitan France",
        "MX" => "Mexico",
        "FM" => "Micronesia",
        "MI" => "Midway Islands",
        "MD" => "Moldova",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar [Burma]",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NL" => "Netherlands",
        "AN" => "Netherlands Antilles",
        "NT" => "Neutral Zone",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "KP" => "North Korea",
        "VD" => "North Vietnam",
        "MP" => "Northern Mariana Islands",
        "NO" => "Norway",
        "OM" => "Oman",
        "PC" => "Pacific Islands Trust Territory",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestinian Territories",
        "PA" => "Panama",
        "PZ" => "Panama Canal Zone",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "YD" => "People's Democratic Republic of Yemen",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn Islands",
        "PL" => "Poland",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RO" => "Romania",
        "RU" => "Russia",
        "RW" => "Rwanda",
        "RE" => "Réunion",
        "BL" => "Saint Barthélemy",
        "SH" => "Saint Helena",
        "KN" => "Saint Kitts and Nevis",
        "LC" => "Saint Lucia",
        "MF" => "Saint Martin",
        "PM" => "Saint Pierre and Miquelon",
        "VC" => "Saint Vincent and the Grenadines",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "CS" => "Serbia and Montenegro",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "ZA" => "South Africa",
        "GS" => "South Georgia and the South Sandwich Islands",
        "KR" => "South Korea",
        "ES" => "Spain",
        "LK" => "Sri Lanka",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard and Jan Mayen",
        "SZ" => "Swaziland",
        "SE" => "Sweden",
        "CH" => "Switzerland",
        "SY" => "Syria",
        "ST" => "São Tomé and Príncipe",
        "TW" => "Taiwan",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania",
        "TH" => "Thailand",
        "TL" => "Timor-Leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad and Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Islands",
        "TV" => "Tuvalu",
        "UM" => "U.S. Minor Outlying Islands",
        "PU" => "U.S. Miscellaneous Pacific Islands",
        "VI" => "U.S. Virgin Islands",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "SU" => "Union of Soviet Socialist Republics",
        "AE" => "United Arab Emirates",
        "GB" => "United Kingdom",
        "US" => "United States",
        "ZZ" => "Unknown or Invalid Region",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VA" => "Vatican City",
        "VE" => "Venezuela",
        "VN" => "Vietnam",
        "WK" => "Wake Island",
        "WF" => "Wallis and Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
        "AX" => "Åland Islands",
    ),

    "shipping_address" => array(
        // Kathmandu
        "KTM_01" => "ABC Courier Service, Baneshwar, Kathmandu",
        "KTM_02" => "Speedy Express, Thamel, Kathmandu",
        "KTM_03" => "Nepal Express Couriers, New Road, Kathmandu",
        "KTM_04" => "Baluwatar Logistics, Baluwatar, Kathmandu",

        // Pokhara
        "PKR_01" => "Mountain Logistics, Lakeside, Pokhara",
        "PKR_02" => "Pokhara Parcel Service, Mahendrapool, Pokhara",
        "PKR_03" => "Himalayan Couriers, Damside, Pokhara",

        // Patan (Lalitpur)
        "PTN_01" => "Patan Courier Hub, Lalitpur",
        "PTN_02" => "Lalitpur Express, Jawalakhel, Lalitpur",
        "PTN_03" => "Durbar Square Couriers, Patan",

        // Biratnagar
        "BRT_01" => "Biratnagar Fast Delivery, Biratnagar",
        "BRT_02" => "Eastern Express Couriers, Biratnagar",
        "BRT_03" => "Birtamod Parcel Service, Biratnagar",

        // Birganj
        "BGJ_01" => "Birganj Parcel Service, Birganj",
        "BGJ_02" => "Terai Express, Birganj",
        "BGJ_03" => "Borderline Couriers, Birganj",

        // Dharan
        "DHR_01" => "Dharan Courier Express, Dharan",
        "DHR_02" => "Sunsari Logistics, Dharan",
        "DHR_03" => "Eastern Hills Couriers, Dharan",

        // Bharatpur
        "BHR_01" => "Bharatpur Quick Ship, Bharatpur",
        "BHR_02" => "Chitwan Express Couriers, Bharatpur",
        "BHR_03" => "Rapid Delivery, Bharatpur",

        // Janakpur
        "JNK_01" => "Janakpur Speed Couriers, Janakpur",
        "JNK_02" => "Mithila Express, Janakpur",
        "JNK_03" => "Ram Janaki Couriers, Janakpur",

        // Dhangadhi
        "DHG_01" => "Dhangadhi Parcel Movers, Dhangadhi",
        "DHG_02" => "Sudurpaschim Express, Dhangadhi",
        "DHG_03" => "Far West Couriers, Dhangadhi",

        // Butwal
        "BTL_01" => "Butwal Express Delivery, Butwal",
        "BTL_02" => "Lumbini Logistics, Butwal",
        "BTL_03" => "Western Parcel Service, Butwal",

        // Mahendranagar
        "MHN_01" => "Mahendranagar Courier Co., Mahendranagar",
        "MHN_02" => "Kanchanpur Express, Mahendranagar",
        "MHN_03" => "Far West Parcel, Mahendranagar",

        // Hetauda
        "HTD_01" => "Hetauda Logistics, Hetauda",
        "HTD_02" => "Makwanpur Couriers, Hetauda",
        "HTD_03" => "Central Nepal Delivery, Hetauda",

        // Madhyapur Thimi
        "MTH_01" => "Madhyapur Thimi Couriers, Madhyapur Thimi",
        "MTH_02" => "Bhaktapur Express, Madhyapur Thimi",
        "MTH_03" => "Newari Parcel Service, Madhyapur Thimi",

        // Triyuga (Gaighat)
        "TRY_01" => "Triyuga Quick Couriers, Triyuga",
        "TRY_02" => "Udayapur Express, Triyuga",
        "TRY_03" => "Gaighat Parcel Service, Triyuga",

        // Inaruwa
        "INR_01" => "Inaruwa Parcel Service, Inaruwa",
        "INR_02" => "Sunsari Express, Inaruwa",
        "INR_03" => "Eastern Terai Couriers, Inaruwa",

        // Nepalgunj
        "NPL_01" => "Nepalgunj Delivery Solutions, Nepalgunj",
        "NPL_02" => "Banke Express Couriers, Nepalgunj",
        "NPL_03" => "Mid-West Parcel Service, Nepalgunj",

        // Siddharthanagar (Bhairahawa)
        "SDN_01" => "Siddharthanagar Fast Couriers, Siddharthanagar",
        "SDN_02" => "Bhairahawa Express, Siddharthanagar",
        "SDN_03" => "Lumbini Parcel Service, Siddharthanagar",

        // Gulariya
        "GLY_01" => "Gulariya Express, Gulariya",
        "GLY_02" => "Bardiya Couriers, Gulariya",
        "GLY_03" => "Terai Parcel Service, Gulariya"
    )

];
